/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface GalleryPhoto {
  'id' : bigint,
  'title' : string,
  'blob' : ExternalBlob,
  'uploadedAt' : bigint,
}
export interface GalleryVideo {
  'id' : bigint,
  'title' : string,
  'blob' : ExternalBlob,
  'uploadedAt' : bigint,
}
export interface GraminProduct {
  'id' : bigint,
  'pricePerKg' : string,
  'productName' : string,
  'pricePerQtl' : string,
  'addedAt' : bigint,
  'quantity' : string,
  'contactNumber' : string,
}
export interface Person {
  'name' : string,
  'profession' : string,
  'description' : [] | [string],
  'phoneNumber' : [] | [string],
}
export interface TransportEntry {
  'id' : bigint,
  'vehicleType' : string,
  'destination' : string,
  'departureTime' : string,
  'addedAt' : bigint,
  'availableSeats' : bigint,
  'contactNumber' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VillageInfo {
  'literacy' : string,
  'area' : string,
  'name' : string,
  'slogan' : string,
  'houses' : string,
  'population' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPerson' : ActorMethod<
    [string, string, [] | [string], [] | [string]],
    undefined
  >,
  'addPhoto' : ActorMethod<[string, ExternalBlob], bigint>,
  'addProduct' : ActorMethod<[string, string, string, string, string], bigint>,
  'addTransport' : ActorMethod<
    [string, string, string, bigint, string],
    bigint
  >,
  'addVideo' : ActorMethod<[string, ExternalBlob], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimAdminRole' : ActorMethod<[string], boolean>,
  'deletePhoto' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deleteTransport' : ActorMethod<[bigint], undefined>,
  'deleteVideo' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPerson' : ActorMethod<[string], [] | [Person]>,
  'getPersons' : ActorMethod<[], Array<Person>>,
  'getPhoto' : ActorMethod<[bigint], [] | [GalleryPhoto]>,
  'getPhotos' : ActorMethod<[], Array<GalleryPhoto>>,
  'getProduct' : ActorMethod<[bigint], [] | [GraminProduct]>,
  'getProducts' : ActorMethod<[], Array<GraminProduct>>,
  'getTransport' : ActorMethod<[bigint], [] | [TransportEntry]>,
  'getTransports' : ActorMethod<[], Array<TransportEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideo' : ActorMethod<[bigint], [] | [GalleryVideo]>,
  'getVideos' : ActorMethod<[], Array<GalleryVideo>>,
  'getVillageInfo' : ActorMethod<[], VillageInfo>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'populateDemoProducts' : ActorMethod<[], undefined>,
  'populateDemoTransports' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateVillageInfo' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];