/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Person = IDL.Record({
  'name' : IDL.Text,
  'profession' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Opt(IDL.Text),
});
export const GalleryPhoto = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'blob' : ExternalBlob,
  'uploadedAt' : IDL.Int,
});
export const GalleryVideo = IDL.Record({
  'id' : IDL.Int,
  'title' : IDL.Text,
  'blob' : ExternalBlob,
  'uploadedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addPerson' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'addPhoto' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Nat], []),
  'addVideo' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Int], []),
  'getPerson' : IDL.Func([IDL.Text], [IDL.Opt(Person)], ['query']),
  'getPersons' : IDL.Func([], [IDL.Vec(Person)], ['query']),
  'getPhoto' : IDL.Func([IDL.Nat], [IDL.Opt(GalleryPhoto)], ['query']),
  'getPhotos' : IDL.Func([], [IDL.Vec(GalleryPhoto)], ['query']),
  'getVideo' : IDL.Func([IDL.Int], [IDL.Opt(GalleryVideo)], ['query']),
  'getVideos' : IDL.Func([], [IDL.Vec(GalleryVideo)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Person = IDL.Record({
    'name' : IDL.Text,
    'profession' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Opt(IDL.Text),
  });
  const GalleryPhoto = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'blob' : ExternalBlob,
    'uploadedAt' : IDL.Int,
  });
  const GalleryVideo = IDL.Record({
    'id' : IDL.Int,
    'title' : IDL.Text,
    'blob' : ExternalBlob,
    'uploadedAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addPerson' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'addPhoto' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Nat], []),
    'addVideo' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Int], []),
    'getPerson' : IDL.Func([IDL.Text], [IDL.Opt(Person)], ['query']),
    'getPersons' : IDL.Func([], [IDL.Vec(Person)], ['query']),
    'getPhoto' : IDL.Func([IDL.Nat], [IDL.Opt(GalleryPhoto)], ['query']),
    'getPhotos' : IDL.Func([], [IDL.Vec(GalleryPhoto)], ['query']),
    'getVideo' : IDL.Func([IDL.Int], [IDL.Opt(GalleryVideo)], ['query']),
    'getVideos' : IDL.Func([], [IDL.Vec(GalleryVideo)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };